name: Build Geth
on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  linter:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true
          cache-dependency-path: go.sum

      - name: Run Linter
        run: go run build/ci.go lint

  tests:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true
          cache-dependency-path: go.sum

      - name: Run Tests
        run: go run build/ci.go test

  build:
    needs: [linter, tests]
    if: |
      always() && 
      (github.event_name == 'push' ||
      (needs.linter.result == 'success' && needs.tests.result == 'success'))

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true
          cache-dependency-path: go.sum

      - name: Set Short SHA
        id: vars
        shell: bash
        run: echo "sha_short=${GITHUB_SHA:0:7}" >> $GITHUB_OUTPUT

      - name: Build Geth
        run: |
          go run build/ci.go install --static ./cmd/geth
          ls build/bin

      - name: Create Compressed Archive
        run: |
          cd build/bin
          tar -czvf geth-${{ steps.vars.outputs.sha_short }}.tar.gz geth

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: geth-release-${{ steps.vars.outputs.sha_short }}
          path: build/bin/geth-${{ steps.vars.outputs.sha_short }}.tar.gz